name: Myfirstworkflow

on : push

jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
            - name: putting code on runner
              run : git clone "https://github.com/Sakshi1786/b17-github-actions.git"

            - name: checking the code
              run : |
                  cd b17-github-actions
                  ls -la
                  chmod  +x new.sh
                   ./new.sh

        
              





