name: Myfirstworkflow

on : workflow_dispatch

jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
            - name: print a message
              run: echo "Hello b17 this is my first workflow"

            
            - name: do thi calculation
              run: expr 10 + 874

            - name: check os info of runner
              run : cat /etc/os-release





